### ISSUE TITLE
lib file not updating

### ISSUE THREAD

**Issue by vidukapoor** [protobi/msexcel-builder#1]
i am updating the lib file with this pakage, but libFunction is not updating with this pakage name

**Comment by protobi-pieter** [comment]
@vidukapoor Can you provide a bit more detail on how installing and the error message?  This fork is mainly intended to merge into the main project branch, so not published on npm.  A few ways to install:
- Download the file `lib/msexcel-builder.js` and save it with other project code (recommended)
- Install directly from github, e.g. `npm install protobi/msexcel-builder --save` (for dev)

**Comment by vidukapoor** [comment]
Thanks "Install directly from github, e.g. npm install protobi/msexcel-builder --save (for dev)"   worked out for me :)

**Comment by protobi-pieter** [comment]
Two notes:
- installing from GitHub links to the latest repo, which is usually great for dev but in production you'll likely want to copy the file into source control. 
- the current repo uses the latest version of JSZip which turned a number of previously synchronous methods into async methods that return a callback.
