### ISSUE TITLE
Number Format Issue

### ISSUE THREAD

**Issue by bongtavas** [protobi/msexcel-builder#10]
I'm currently having an issue when setting number formats in different cells.
The number format does not show when I open the exported file in Excel. Here is the code I use to set a specific cell's number format. 
```
{
fill : { type: "solid", fgColor: "00FFFFFF", bgColor: "-" },
font : { name: "Calibri", sz: 8 },
numberFormat: "0.00",
set:0.5524822392015282,
}
```

For some reason, the numberFormat property works when I set ALL of the cells to use the same numberFormat (ex: '0.00').

**Comment by protobi-pieter** [comment]
thanks for reporting, I can reproduce that.  The numberFormat values get correctly looked up and saved to `this.styles['numfmt_' + col + '_' + row] ` but the issue appears to be how msexcel-builder serializes it to XML.  I think it has to do with this line, and related to a prior mystery where a fill has to be specified for numberFormat to work.   I should have time to look at this later this week.
```
    for o in @mstyle
      e = cs.ele('xf',{numFmtId: o.numfmt_id||'0',fontId:(o.font_id-1),fillId:o.fill_id+1,borderId:(o.bder_id-1),xfId:'0'})
```

**Comment by LIMRoss** [comment]
Has there been any  progress on this front? I didn't notice all the issues with number formatting until I had converted over to this project. Luckily I had a number to text formatter that I use for my table generator to hold me over while I look at the source.
