### ISSUE TITLE
Support for cell formula?

### ISSUE THREAD

**Issue by bongtavas** [protobi/msexcel-builder#11]
Currently the library does not support adding formula in a cell. I could submit a PR but I don't know where to start. My only resource for now is this [Office Open XML](https://blogs.msdn.microsoft.com/chrisrae/2010/09/25/where-is-the-documentation-for-offices-docxxlsxpptx-formats-part-1-office-2007/). Can someone guide me on how to implement this? Badly need it for a project =)

**Comment by protobi-pieter** [comment]
@RomelioTavas Thanks, this is an important feature to support, we're on it. What's your timeline?  Can DM direct at support@protobi.com.

**Comment by protobi-pieter** [comment]
if urgent, there's also the commercial version of SheetJS which has great formula support.

**Comment by bongtavas** [comment]
Alright! Thanks. Still have to confirm with my lead regarding the project timeline. I'll also give SheetJS a try.

**Comment by protobi-pieter** [comment]
Support for formulas implemented in present commit.
