### ISSUE TITLE
Currency Format Not Supported

### ISSUE THREAD

**Issue by JonnoFTW** [protobi/msexcel-builder#14]
I want to format a cell as currency: `'$#,###.00'`, but when I do this I get the error:

```
msexcel-builder.js:629 Uncaught Number format $#,###.00 not found.  Custom number formats not implemented yet
```

Is there any way I can render a number as currency?

**Comment by protobi-pieter** [comment]
That should be possible to add.

As a short expedient can you work with one of the built in formats?

```js
 numberFormats: {
    0: 'General'
    1: '0'
    2: '0.00'
    3: '#,##0'
    4: '#,##0.00'
    9: '0%'
    10: '0.00%'
    11: '0.00E+00'
    12: '# ?/?'
    13: '# ??/??'
    14: 'm/d/yy'
    15: 'd-mmm-yy'
    16: 'd-mmm'
    17: 'mmm-yy'
    18: 'h:mm AM/PM'
    19: 'h:mm:ss AM/PM'
    20: 'h:mm'
    21: 'h:mm:ss'
    22: 'm/d/yy h:mm'
    37: '#,##0 ;(#,##0)'
    38: '#,##0 ;[Red](#,##0)'
    39: '#,##0.00;(#,##0.00)'
    40: '#,##0.00;[Red](#,##0.00)'
    45: 'mm:ss'
    46: '[h]:mm:ss'
    47: 'mmss.0'
    48: '##0.0E+0'
    49: '@'
    56: '"上午/下午 "hh"時"mm"分"ss"秒 "'
  }
```

Below is a code snippet from a very different library js-xlsx that does this.  You may be able see how this works and add the functionality here (ideally with a test and pull request).  

The basic idea is it looks up to see if you have a standard format, if so it uses that.  If it doesn't match you register a new number format, giving it a new incremental id.  You have to escape certain characters so they don't interfere with XML representation underneath.  

```js
       _addNumFmt: function (numFmt) {
        if (!numFmt) { return 0; }

        if (typeof numFmt == 'string') {
          var numFmtIdx = fmt_table[numFmt];
          if (numFmtIdx >= 0) {
            return numFmtIdx; // we found a match against built in formats
          }
        }

        if (/^[0-9]+$/.exec(numFmt)) {
          return numFmt; // we're matching an integer against some known code
        }
        numFmt = numFmt
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');

        var $numFmt = XmlNode('numFmt')
            .attr('numFmtId', (++customNumFmtId))
            .attr('formatCode', numFmt);

        this.$numFmts.append($numFmt);

        var count = this.$numFmts.children().length;
        this.$numFmts.attr('count', count);
        return customNumFmtId ;
      },
```

**Comment by JonnoFTW** [comment]
Well given there's no currency formatter in `numberFormats`, I can't work with what's there. I'll look at doing a fix for this library based off the code you gave (I might take inspiration from some other more well maintained projects like [excel4node](https://github.com/natergj/excel4node) or [exceljs](https://github.com/exceljs/exceljs).

**Comment by JonnoFTW** [comment]
@pietersv I have an issue where numberformat styles are not being applied at all.  I've tried both `set` and `numberFormat` methods of the Sheet object.

I've inspected my sheet object and can see things like this:

```
algn_6_3: "center"
valgn_6_3: "bottom"
numfmt_2_5: 3
numfmt_3_5: 3
numfmt_4_5: 3
numfmt_5_5: 3
numfmt_6_5: 3
numfmt_2_11: "56"
```

The alignment styles appear in excel, but the number formats do not.
