### ISSUE TITLE
Hint to use compression..

### ISSUE THREAD

**Issue by Zhenyi-Wang** [protobi/msexcel-builder#19]
In addtion to the README doc, if you want to 'truly' compress the output xlsx file, an extra option 

> compression:'DEFLATE'

should be added when you call jszip.generateAsync(), for example

```
jszip.generateAsync(
{
  compression:'DEFLATE',
  type: "blob", 
  mimeType: 'application/vnd.ms-excel;'
}).then.....
```
This will (in many cases significantly) reduce the output file size.

**Comment by protobi-pieter** [comment]
In the present release files may now be now be saved compressed:

```
 workbook.save("/tmp/workbook.xlsx", {compressed: true}, function(err) {
      if (err) throw err;
      console.log("open \"" + path + "\"");
   });
```
