### ISSUE TITLE
Excel-page setup

### ISSUE THREAD

**Issue by vidukapoor** [protobi/msexcel-builder#3]
Is there any option to set-up the generated excel sheet "fit to one page" i.e in the A4

**Comment by protobi-pieter** [comment]
The present release has additional features to set page scale (on screen) and print scale, as integers representing percents.  


* zoomScaleNormal: 52 // zoom scale for printing
* zoomScale: 52 // zoom scale for on screen

These option names are not that clear, they're chosen to parallel the attribute names in the Office OpenXML spec underneath.

Additional options allow you to set page breaks and repeating rows/columns when printing.
