### ISSUE TITLE
Published version of this fork?

### ISSUE THREAD

**Issue by glenjamin** [protobi/msexcel-builder#4]
I've been researching the easiest way to generate an excel sheet with colours and formatting, and this looks to be in good shape for that purpose.

Is there a version you publish to npm anywhere?

**Comment by amirelemam** [comment]
https://www.npmjs.com/package/msexcel-builder-protobi

**Comment by glenjamin** [comment]
Thanks, looks like it's missing the latest change, but up-to-date otherwise 👍

**Comment by protobi-pieter** [comment]
@glenjamin My strategy for `msexcel-builder` has been to submit PRs and keep the main branch up to date.  That said, the `lib/msexcel-builder.js` file is small and easily minified further, so you can just copy it into your source.
