### ISSUE TITLE
Error on compile: Can't resolve child_process

### ISSUE THREAD

**Issue by ralexand56** [protobi/msexcel-builder#6]

**Comment by protobi-pieter** [comment]
@ralexand56 Thanks for reporting.  Can you provide more details on how to replicate?  I just checked just now and was able to run the following without issue:
```bash
git clone https://github.com/protobi/msexcel-builder.git
cd msexcel-builder
npm install 
npm test
```

**Comment by ralexand56** [comment]
Think I was mistaken. Thought the component could run from a browser. Guess it requires node.

**Comment by protobi-pieter** [comment]
I believe there's nothing about this code that couldn't run in the browser, it's just that it's not yet packaged in such a way as to either include jszip and xmlbuilder in the build or recognize them if already loaded within the window.  That would be a very useful contribution.

**Comment by ralexand56** [comment]
OK, I'll take a look. Thanks!

**Comment by protobi-pieter** [comment]
The most recent commit packages msexcel-builder for use in the browser.  An example is included in the README and `test/index.html` 

The dependencies are `xmlbuilder` and `jszip`.  For right now, these dependencies are included in the rep as `lib/xmlbuilder.js` and `lib/jszip.js`.  Ideally, these would be installed via npm and managed via package.json with semver constraints.  Setting that up would be a useful contribution.

The msexcelbuilder is just 37kb.  JSZip is 99kb zipped and xmlbuilder is 99kb unzipped.

**Comment by ikochetkov** [comment]
How to solve this error?
../node_modules/msexcel-builder/lib/msexcel-builder.js
Module not found: Can't resolve 'child_process' in 'C:\PNL\node_modules\msexcel-builder\lib'

**Comment by protobi-pieter** [comment]
@ikochetkov Thanks for reporting this. Any hints to help me replicate this would be useful (e.g. OS, Node.js or browser, etc.).  Can message  support at protobi.com directly if any of those details can't be posted on an open source issue.
